In [1]:
import torch
import numpy as np

In [2]:
z= torch.arange(20)

z.shape, z
 # Vector shape (1 dimension)

(torch.Size([20]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]))

#### Reshape

In [3]:
## Add an extra column dimension
 # The below code shows we want to shape a tensor from a 1D vector to a 2D matrix
 # The matrix should have 1 row and 'n' columns
 # 'n' depends on the length of the 1D matrix, otherwise, reshaping will bring an error
z_reshaped= z.reshape(1, len(z))
 
z_reshaped.shape, z_reshaped

(torch.Size([1, 20]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19]]))

In [4]:
## Add extra row dimensions
 # The rule of 'n' still applies
z_reshaped_row= z.reshape(len(z), 1)
z_reshaped_row.shape, z_reshaped_row

(torch.Size([20, 1]),
 tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13],
         [14],
         [15],
         [16],
         [17],
         [18],
         [19]]))

In [5]:
## Basically, the new reshaped tensor should be able to hold the....
## ...same no. of elements as the original tensor
z_shaped= z.reshape(4,5)
z_shaped1= z.reshape(10,2)
print(z_shaped.shape)
print(z_shaped)
print()
print(z_shaped1.shape)
print(z_shaped1)




torch.Size([4, 5])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

torch.Size([10, 2])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])


#### Change View

In [6]:
z

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [7]:
## Changing the view
v= z.view(4,5)
v.shape, v

(torch.Size([4, 5]),
 tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]))

In [8]:
## Changing the viewing tensor 'v' also changes the orignal tensor z
## This is because the view of a tensor shares the same memory as the original tensor
## Here we change the element on the first row of the third column
v[1,3]= 300
v, z


(tensor([[  0,   1,   2,   3,   4],
         [  5,   6,   7, 300,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]]),
 tensor([  0,   1,   2,   3,   4,   5,   6,   7, 300,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19]))

#### Stack Tensors on top of each other
Concatenate tensors along a new dimension

In [9]:
z.shape, z


(torch.Size([20]),
 tensor([  0,   1,   2,   3,   4,   5,   6,   7, 300,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19]))

In [10]:
z_stacked= torch.stack([z, z])
z_stacked.shape, z_stacked
 # The individual vector tensors are stacked on top of each other to create a mattrix tensor
 # New (row) dimension is added here

(torch.Size([2, 20]),
 tensor([[  0,   1,   2,   3,   4,   5,   6,   7, 300,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19],
         [  0,   1,   2,   3,   4,   5,   6,   7, 300,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19]]))

In [11]:
## We can specify a target dimension we want the stacked tensor to appear in
 # Default is dim= 0 (row stacking)
 # dim= 1 peforms column stacking
z_stacked1= torch.stack([z,z], dim= 1)
z_stacked1.shape, z_stacked1

(torch.Size([20, 2]),
 tensor([[  0,   0],
         [  1,   1],
         [  2,   2],
         [  3,   3],
         [  4,   4],
         [  5,   5],
         [  6,   6],
         [  7,   7],
         [300, 300],
         [  9,   9],
         [ 10,  10],
         [ 11,  11],
         [ 12,  12],
         [ 13,  13],
         [ 14,  14],
         [ 15,  15],
         [ 16,  16],
         [ 17,  17],
         [ 18,  18],
         [ 19,  19]]))

#### Squeezing
Removes all dimensions of size 1 from the input tensor.

In [12]:
## Original tensor
s= torch.rand([1,15])
print('Original tensor and tensor shape')
print(s.shape, s)
print('\nSqueezed tensor and tensor shape')
print(s.squeeze().shape, s.squeeze())

Original tensor and tensor shape
torch.Size([1, 15]) tensor([[0.2277, 0.0444, 0.0472, 0.4922, 0.8394, 0.9535, 0.5476, 0.2051, 0.5645,
         0.3095, 0.4114, 0.0684, 0.0987, 0.7165, 0.4741]])

Squeezed tensor and tensor shape
torch.Size([15]) tensor([0.2277, 0.0444, 0.0472, 0.4922, 0.8394, 0.9535, 0.5476, 0.2051, 0.5645,
        0.3095, 0.4114, 0.0684, 0.0987, 0.7165, 0.4741])


In [13]:
s1= torch.rand([4, 5, 1, 3, 1])
 # 5 dimensional tensor
print('Original tensor shape')
print(s1.shape)
print('\nSqueezed tensor shape')
print(s1.squeeze().shape)

Original tensor shape
torch.Size([4, 5, 1, 3, 1])

Squeezed tensor shape
torch.Size([4, 5, 3])


#### Unsqueeze
Adds a dimension of size 1 to the tensor's shape.

In [14]:
s_squeezed= s1.squeeze()
print('Original Tensor shape')
print(s_squeezed.shape)

print('\nNew tesnor shape (dim= 0)')
print(s_squeezed.unsqueeze(dim= 0).shape)

print('\nUnsqueezed tensor shape (dim= 1)')
print(s_squeezed.unsqueeze(dim= 1).shape)

print('\nUnsqueezed tensor shape (dim= 1)')
print(s_squeezed.unsqueeze(dim= 1).shape)

print('\nUnsqueezed tensor shape (dim= 3)')
print(s_squeezed.unsqueeze(dim= 3).shape)

Original Tensor shape
torch.Size([4, 5, 3])

New tesnor shape (dim= 0)
torch.Size([1, 4, 5, 3])

Unsqueezed tensor shape (dim= 1)
torch.Size([4, 1, 5, 3])

Unsqueezed tensor shape (dim= 1)
torch.Size([4, 1, 5, 3])

Unsqueezed tensor shape (dim= 3)
torch.Size([4, 5, 3, 1])


#### Permute
- Can be used to change (swap) the order of the dimensions of a tensor.
- Common when working with image tensors

In [15]:
## We create an image tensor [height, width, color channels]
p= torch.rand([220, 221, 3])
p_permuted= p.permute(2, # dim 2 is mapped/swapped to the first index
                      0, # dim 0 is swapped to the 2nd index
                      1) # dim 1 is swapped to the last/3rd index

print(f'Previous shape {p.shape}')
print(f'New shape: {p_permuted.shape}')

print('\nChecking whether changes are made')
print(f'Original: {p[0,0,2]}') # Row 0, column 0, matrix 2
print(f'Permuted: {p_permuted[0,0,2]}')

Previous shape torch.Size([220, 221, 3])
New shape: torch.Size([3, 220, 221])

Checking whether changes are made
Original: 0.025391995906829834
Permuted: 0.27365535497665405


### Indexing (Selecting data from tensors)

In [16]:
tensor= torch.arange(1,20).reshape(1, 3, 3)
tensor.shape, tensor
 # Tensor shape is 1 matrix, 3 rows, 3 columns

RuntimeError: shape '[1, 3, 3]' is invalid for input of size 19

In [ ]:
## 2nd value on the middle bracket
tensor[0, 1, 1], tensor[0][1][1]

(tensor(5), tensor(5))

In [ ]:
## Last value of the last bracket
tensor[0, 2, 2]

tensor(9)

In [ ]:
## The entire first row
tensor[0, 0, :]

tensor([1, 2, 3])

In [ ]:
## The entire first column
tensor[0,:, 0]

tensor([1, 4, 7])

In [ ]:
## The second and third row
tensor[0, 1:3, :]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [ ]:
## The entire last column
tensor[0,:,2]

tensor([3, 6, 9])

### PyTorch Tensors & NumPy
NumPy is a popular scientific numerical computing library. Because of this, PyTorch has the functionality to interact with it.
- If the data is in NumPy and we want it in PyTorch -> `torch.from_numpy(array_data)`
- If the data is in PyTorch and we want it in NumPy -> `torch.Tensor.numpy(tensor_data)`

They dont share memory meaning changing one will not change the other.

In [ ]:
## NumPy array to tensor
array= np.random.random([3,3])
print('Array')
print(array)

tensor= torch.from_numpy(array)
print('\nTensor')
print(tensor)
 # Datatype of the converted tensor is float64 as is the default datatype for NumPy arrays
 # Default datatype for PyTorch tensors is float32

Array
[[0.2376379  0.22782564 0.69813364]
 [0.26976439 0.928965   0.94240912]
 [0.23268163 0.94963518 0.93065838]]

Tensor
tensor([[0.2376, 0.2278, 0.6981],
        [0.2698, 0.9290, 0.9424],
        [0.2327, 0.9496, 0.9307]], dtype=torch.float64)


In [ ]:
## Tensor to NumPy array
print('Tensor')
print(tensor)

print('\nArray')
print(torch.Tensor.numpy(tensor))

Tensor
tensor([[0.2376, 0.2278, 0.6981],
        [0.2698, 0.9290, 0.9424],
        [0.2327, 0.9496, 0.9307]], dtype=torch.float64)

Array
[[0.2376379  0.22782564 0.69813364]
 [0.26976439 0.928965   0.94240912]
 [0.23268163 0.94963518 0.93065838]]
