## PyTorch Fundamentals 3
### Reproducibility
- Entails trying to take the random out of random to ensure the experiment and results can be replicated.
- In short, it's how a neural network learns
   - Start with random numbers
   - Tensor operations
   - Update random numbers to try and make them of the data
   - Repeat
- To reduce randomness in neural networks, comes the concept of **random seed**. What it does is *flavours* the randomness.



In [1]:
import torch


In [2]:
## Create two random tensors
random_A= torch.rand(3,4)
random_B= torch.rand(3,4)

print('A:', random_A)
print('B:', random_B)
print('\n',random_A == random_B)

A: tensor([[0.3800, 0.7958, 0.9141, 0.2762],
        [0.3013, 0.9508, 0.2706, 0.3371],
        [0.3863, 0.2972, 0.3110, 0.6848]])
B: tensor([[0.2747, 0.3186, 0.7778, 0.4929],
        [0.2139, 0.2583, 0.8954, 0.0457],
        [0.1885, 0.2728, 0.8619, 0.0564]])

 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
## Random Tensors with seed
random_seed= 42

torch.manual_seed(random_seed)
random_C= torch.rand(3,4)
 # Note that random seed function needs to be run every time a random tensor is contructed

torch.manual_seed(random_seed)
random_D= torch.rand(3,4)

print('C:', random_C)
print('D:', random_D)
print('\n', random_C==random_D)

C: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
D: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Accessing a GPU
- GPUs/TPUs can enable faster Tensor computations.
- Provided primarily by NVIDIA's CUDA toolkit or from Google (Colab). PyTorch can work with either for faster operations
- Getting a GPU
   - Google Colab pro (not free)
   - Set up and use your own GPU (can be technical to set up and costly to purchase the GPU and other hardware required)
   - Use cloud computing platforms (AWS, GCP, Azure)

*For 2 and 3 refer to PyTorch setup documentation*

In [4]:
## Run the below code once connected to the GPU/TPU to check specifications
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
## Check for GPU access wth PyTorch
torch.cuda.is_available()

False

In [6]:
## Set up device agnostic code
# In the event PyTorch disconnects from CUDA
device= 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [7]:
## Count no. of devices
torch.cuda.device_count()

0

In [14]:
## Using the GPU
## Putting the tensors and models on the set device
 # GPU for faster computation, CPU if that is the only option available
tensor= torch.rand(2,2)
tensor_on_device= tensor.to(device)
tensor_on_device, tensor_on_device.device

(tensor([[0.5472, 0.0062],
         [0.9516, 0.0753]]),
 device(type='cpu'))

In [17]:
## Note that if the tensor is on a GPU. You cannot convert it to a Numpy array
## To avoid an eror convert the Tensor to run on CPU
tensor_cpu= tensor_on_device.cpu().numpy()
tensor_cpu, type(tensor_cpu)

(array([[0.54719156, 0.00616044],
        [0.95155454, 0.07526588]], dtype=float32),
 numpy.ndarray)